test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: canvas
  password: your_password
  timeout: 5000
  shard1: canvas_test_shard_1
  shard2: canvas_test_shard_2

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  password: your_password
  timeout: 5000
  secondary:
    replica: true
    username: canvas_readonly_user

# This assumes the standard port, :5432. The Cloud Sql Auth Proxy
# should be listening on that port, ready for connections.
production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: 127.0.0.1
  username: canvas
  # This should be inserted safely before canvas starts.
  #password: ''
  timeout: 5000

